export const FINANCIAL_TIPS = [
  "Sisihkan minimal 10% dari gaji untuk tabungan sebelum belanja.",
  "Catat setiap pengeluaran, sekecil apapun, untuk melacak kebocoran dana.",
  "Gunakan metode 50/30/20: 50% kebutuhan, 30% keinginan, 20% tabungan.",
  "Hindari belanja impulsif dengan menunggu 24 jam sebelum membeli barang non-esensial.",
  "Siapkan dana darurat minimal 3-6 kali pengeluaran bulanan.",
  "Bandingkan harga di minimal 3 toko sebelum membeli barang mahal.",
  "Masak di rumah lebih sering untuk menghemat biaya makan di luar.",
  "Matikan lampu dan alat elektronik yang tidak digunakan untuk hemat tagihan.",
  "Gunakan transportasi umum atau jalan kaki jika jarak memungkinkan.",
  "Berhenti berlangganan layanan yang jarang Anda gunakan.",
  "Investasikan waktu untuk belajar literasi keuangan setiap minggu.",
  "Jangan pernah berhutang untuk konsumsi barang yang nilainya turun.",
  "Mulai investasi sedini mungkin untuk memanfaatkan bunga majemuk.",
  "Diversifikasikan investasi Anda untuk mengurangi risiko.",
  "Tinjau kembali anggaran bulanan Anda di akhir setiap bulan.",
  "Bawa botol minum sendiri saat bepergian untuk hemat biaya minum.",
  "Gunakan daftar belanja saat ke supermarket agar tidak membeli yang tidak perlu.",
  "Manfaatkan diskon dan promo, tapi jangan membeli hanya karena sedang diskon.",
  "Perbaiki barang yang rusak daripada langsung membeli yang baru.",
  "Tetapkan tujuan keuangan yang spesifik, terukur, dan realistis.",
  "Bayar tagihan tepat waktu untuk menghindari denda keterlambatan.",
  "Gunakan kartu kredit dengan bijak, bayar lunas setiap bulan.",
  "Cari penghasilan tambahan dari hobi atau keahlian Anda.",
  "Jangan membandingkan gaya hidup Anda dengan orang lain di media sosial.",
  "Ajarkan anak-anak tentang nilai uang sejak dini.",
  "Evaluasi asuransi Anda secara berkala untuk memastikan perlindungan optimal.",
  "Beli barang berkualitas yang tahan lama meskipun harganya sedikit lebih mahal.",
  "Gunakan aplikasi atau buku catatan untuk memantau aset dan hutang.",
  "Hindari gaya hidup 'gali lubang tutup lubang'.",
  "Rayakan pencapaian keuangan kecil Anda sebagai motivasi.",
  "Pahami perbedaan antara kebutuhan dan keinginan.",
  "Jangan menaruh semua telur dalam satu keranjang (diversifikasi).",
  "Baca buku tentang manajemen keuangan pribadi.",
  "Gunakan uang tunai untuk belanja harian agar lebih terasa pengeluarannya.",
  "Siapkan dana khusus untuk hari raya atau liburan jauh-jauh hari.",
  "Cek saldo rekening secara berkala untuk menghindari biaya admin tak terduga.",
  "Jangan mudah tergiur dengan investasi yang menjanjikan keuntungan tidak masuk akal.",
  "Zakat dan sedekah tidak akan membuat Anda miskin, justru membawa berkah.",
  "Gunakan fitur auto-debet untuk menabung agar lebih disiplin.",
  "Beli baju saat sedang pergantian musim atau diskon besar.",
  "Rawat aset Anda (kendaraan, gadget) agar tidak cepat rusak.",
  "Pahami biaya tersembunyi saat membeli aset (pajak, perawatan).",
  "Jangan meminjamkan uang jika Anda sendiri sedang kesulitan keuangan.",
  "Gunakan perpustakaan atau pinjam buku daripada selalu membeli baru.",
  "Cari hiburan gratis seperti taman kota atau museum di hari tertentu.",
  "Kurangi kebiasaan jajan kopi atau snack di luar rumah.",
  "Gunakan energi matahari atau ventilasi alami untuk hemat listrik.",
  "Pahami profil risiko Anda sebelum mulai berinvestasi saham atau kripto.",
  "Jangan panik saat pasar investasi turun, tetap pada rencana jangka panjang.",
  "Konsultasikan rencana keuangan besar dengan pasangan atau keluarga.",
  "Pastikan Anda memiliki asuransi kesehatan yang memadai.",
  "Gunakan poin reward atau cashback dari transaksi Anda.",
  "Jangan biarkan uang menganggur di rekening tabungan biasa, pindahkan ke instrumen lain.",
  "Pelajari cara mengisi SPT pajak sendiri agar lebih paham aturan.",
  "Hindari lingkungan yang mendorong Anda untuk boros.",
  "Fokus pada menambah penghasilan, bukan hanya memotong pengeluaran.",
  "Gunakan aplikasi perbandingan harga untuk belanja online.",
  "Jangan membeli gadget terbaru hanya karena gengsi.",
  "Siapkan dana pendidikan anak sejak mereka lahir.",
  "Pahami kontrak pinjaman dengan teliti sebelum menandatangani.",
  "Gunakan diskon kartu member untuk belanja rutin.",
  "Beli barang dalam jumlah besar (bulk) untuk barang yang awet dan sering dipakai.",
  "Jangan lupakan biaya hiburan dalam anggaran agar tidak stres.",
  "Gunakan transportasi online hanya saat mendesak.",
  "Berhenti merokok atau kurangi kebiasaan buruk yang menguras kantong.",
  "Tanam sayuran atau bumbu dapur sendiri di rumah jika ada lahan.",
  "Gunakan air secukupnya dan perbaiki kebocoran pipa segera.",
  "Pahami cara kerja kartu kredit dan bunga yang dikenakan.",
  "Jangan berhutang kepada teman atau keluarga jika tidak sangat mendesak.",
  "Miliki asuransi jiwa jika Anda adalah pencari nafkah utama.",
  "Gunakan tabungan emas sebagai alternatif investasi aman.",
  "Pelajari analisis fundamental sederhana sebelum beli saham.",
  "Jangan terpengaruh FOMO (Fear Of Missing Out) dalam investasi.",
  "Siapkan dana untuk perawatan kesehatan gigi secara rutin.",
  "Gunakan kupon atau voucher saat makan di restoran.",
  "Jangan biarkan kartu kredit mencapai limit maksimal.",
  "Pahami biaya admin bank dan cari yang paling kompetitif.",
  "Gunakan uang bonus atau THR untuk melunasi hutang atau investasi.",
  "Jangan membeli mobil baru jika mobil bekas masih layak pakai.",
  "Pelajari cara mengelola pajak UMKM jika Anda punya bisnis sampingan.",
  "Gunakan asuransi perjalanan saat bepergian ke luar negeri.",
  "Jangan lupakan inflasi saat menghitung target dana pensiun.",
  "Gunakan aplikasi pengingat tagihan agar tidak lupa bayar.",
  "Jangan membeli barang hanya karena 'mumpung lagi murah'.",
  "Pahami hak-hak Anda sebagai konsumen keuangan.",
  "Gunakan dana darurat hanya untuk keadaan yang benar-benar darurat.",
  "Jangan berinvestasi menggunakan uang panas (uang untuk kebutuhan pokok).",
  "Pelajari cara negosiasi gaji atau harga barang.",
  "Gunakan fitur 'wishlist' dan tunggu diskon sebelum membeli.",
  "Jangan biarkan emosi mengendalikan keputusan keuangan Anda.",
  "Siapkan dana untuk perbaikan rumah secara berkala.",
  "Gunakan asuransi kendaraan untuk melindungi aset transportasi Anda.",
  "Jangan lupakan biaya pajak bumi dan bangunan (PBB) setiap tahun.",
  "Gunakan aplikasi e-wallet dengan bijak, jangan biarkan saldo mengendap terlalu banyak.",
  "Pelajari cara kerja reksadana sebagai langkah awal investasi.",
  "Jangan membeli barang KW, lebih baik merk lokal yang berkualitas.",
  "Gunakan promo 'buy 1 get 1' dengan teman untuk berbagi biaya.",
  "Jangan biarkan hutang kartu kredit berbunga-bunga.",
  "Pahami manfaat dan risiko asuransi unit link.",
  "Gunakan dana sosial untuk membantu sesama secara terencana.",
  "Jangan lupakan biaya parkir dan tol dalam anggaran transportasi.",
  "Gunakan fitur 'incognito' saat mencari tiket pesawat online.",
  "Jangan membeli barang yang tidak Anda pahami cara kerjanya.",
  "Pelajari cara membuat laporan keuangan sederhana untuk diri sendiri.",
  "Gunakan asuransi properti untuk melindungi rumah dari risiko kebakaran.",
  "Jangan lupakan biaya servis rutin kendaraan agar tetap awet.",
  "Gunakan aplikasi cashback saat belanja di e-commerce.",
  "Jangan biarkan uang receh tercecer, kumpulkan dalam celengan.",
  "Pahami aturan waris dan wasiat untuk perencanaan masa depan.",
  "Gunakan dana hiburan untuk pengalaman, bukan hanya barang.",
  "Jangan lupakan biaya langganan aplikasi di smartphone.",
  "Gunakan fitur 'limit' pada aplikasi perbankan untuk keamanan.",
  "Pelajari cara investasi di pasar uang untuk likuiditas tinggi.",
  "Jangan membeli barang hanya karena sedang tren.",
  "Gunakan asuransi pendidikan untuk menjamin masa depan anak.",
  "Jangan lupakan biaya administrasi saat melakukan transfer antar bank.",
  "Gunakan aplikasi investasi yang terdaftar dan diawasi OJK.",
  "Jangan biarkan tagihan kartu kredit menumpuk.",
  "Pahami perbedaan antara investasi dan spekulasi.",
  "Gunakan dana cadangan untuk peluang investasi yang muncul tiba-tiba.",
  "Jangan lupakan biaya pemeliharaan gadget (case, screen protector).",
  "Gunakan fitur 'auto-save' pada aplikasi belanja.",
  "Pelajari cara mengelola keuangan saat terjadi krisis ekonomi.",
  "Jangan membeli barang yang hanya akan dipakai sekali.",
  "Gunakan asuransi kesehatan tambahan jika plafon kantor kurang.",
  "Jangan lupakan biaya iuran warga atau keamanan lingkungan.",
  "Gunakan aplikasi pencatat hutang jika Anda meminjamkan uang.",
  "Jangan biarkan gaya hidup meningkat seiring kenaikan gaji (lifestyle creep).",
  "Pahami cara kerja obligasi negara sebagai investasi aman.",
  "Gunakan dana khusus untuk hobi agar tidak mengganggu pos lain.",
  "Jangan lupakan biaya perpanjangan SIM dan STNK.",
  "Gunakan fitur 'split bill' saat makan bersama teman.",
  "Pelajari cara mengoptimalkan pengembalian pajak (tax refund).",
  "Jangan membeli barang yang perawatannya sangat mahal.",
  "Gunakan asuransi penyakit kritis untuk perlindungan ekstra.",
  "Jangan lupakan biaya kuota internet untuk bekerja dari rumah.",
  "Gunakan aplikasi dompet digital yang memberikan banyak promo.",
  "Jangan biarkan uang tunai terlalu banyak di dompet.",
  "Pahami risiko investasi di sektor properti.",
  "Gunakan dana darurat untuk biaya medis yang tidak terduga.",
  "Jangan lupakan biaya kado untuk acara pernikahan atau ulang tahun.",
  "Gunakan fitur 'budgeting' pada aplikasi bank digital.",
  "Pelajari cara investasi di pasar modal melalui aplikasi sekuritas.",
  "Jangan membeli barang yang tidak memiliki garansi resmi.",
  "Gunakan asuransi tanggung gugat jika Anda memiliki bisnis.",
  "Jangan lupakan biaya keanggotaan gym atau komunitas.",
  "Gunakan aplikasi pembanding asuransi untuk mendapatkan premi terbaik.",
  "Jangan biarkan investasi Anda tidak terpantau.",
  "Pahami cara kerja deposito dan penalti pencairan awal.",
  "Gunakan dana khusus untuk pengembangan diri (kursus, seminar).",
  "Jangan lupakan biaya kirim (ongkir) saat belanja online.",
  "Gunakan fitur 'round up' pada aplikasi tabungan.",
  "Pelajari cara mengelola keuangan keluarga secara transparan.",
  "Jangan membeli barang yang hanya untuk pamer.",
  "Gunakan asuransi perjalanan tahunan jika sering bepergian.",
  "Jangan lupakan biaya langganan TV kabel atau streaming film.",
  "Gunakan aplikasi manajemen password untuk keamanan akun keuangan.",
  "Jangan biarkan hutang konsumtif menguasai hidup Anda.",
  "Pahami risiko investasi di bisnis startup.",
  "Gunakan dana sosial untuk membantu keluarga yang membutuhkan.",
  "Jangan lupakan biaya administrasi penarikan uang di ATM.",
  "Gunakan fitur 'lock' pada kartu kredit jika tidak digunakan.",
  "Pelajari cara investasi di instrumen syariah jika sesuai prinsip Anda.",
  "Jangan membeli barang yang tidak Anda butuhkan sekarang.",
  "Gunakan asuransi kesehatan untuk orang tua Anda.",
  "Jangan lupakan biaya renovasi kecil di rumah.",
  "Gunakan aplikasi pelacak paket untuk memastikan barang belanjaan sampai.",
  "Jangan biarkan emosi saat sedih membuat Anda belanja berlebihan (retail therapy).",
  "Pahami cara kerja peer-to-peer lending dan risikonya.",
  "Gunakan dana khusus untuk zakat mal dan fitrah.",
  "Jangan lupakan biaya iuran kartu kredit tahunan.",
  "Gunakan fitur 'virtual card' untuk transaksi online yang lebih aman.",
  "Pelajari cara mengelola keuangan saat masa pensiun tiba.",
  "Jangan membeli barang yang tidak bisa Anda jual kembali dengan harga layak.",
  "Gunakan asuransi jiwa berjangka (term life) yang lebih murah.",
  "Jangan lupakan biaya pemeliharaan taman atau kolam di rumah.",
  "Gunakan aplikasi perbandingan bunga pinjaman.",
  "Jangan biarkan uang Anda 'tidur' di bawah bantal.",
  "Pahami risiko investasi di komoditas seperti minyak atau gandum.",
  "Gunakan dana darurat untuk biaya perbaikan kendaraan yang mendadak.",
  "Jangan lupakan biaya iuran sekolah atau kuliah.",
  "Gunakan fitur 'scheduled transfer' untuk bayar cicilan.",
  "Pelajari cara investasi di pasar valuta asing (forex) dengan hati-hati.",
  "Jangan membeli barang yang hanya akan menambah tumpukan di rumah.",
  "Gunakan asuransi kesehatan internasional jika sering ke luar negeri.",
  "Jangan lupakan biaya langganan koran atau majalah digital.",
  "Gunakan aplikasi pengelola pengeluaran yang bisa sinkron antar perangkat.",
  "Jangan biarkan hutang piutang merusak hubungan pertemanan.",
  "Pahami risiko investasi di barang koleksi (jam tangan, tas mewah).",
  "Gunakan dana khusus untuk perayaan ulang tahun anak.",
  "Jangan lupakan biaya administrasi saat menutup rekening bank.",
  "Gunakan fitur 'biometric login' untuk keamanan aplikasi keuangan.",
  "Pelajari cara mengelola keuangan saat menjadi orang tua tunggal.",
  "Jangan membeli barang yang biaya operasionalnya sangat tinggi.",
  "Gunakan asuransi jiwa seumur hidup (whole life) untuk warisan.",
  "Jangan lupakan biaya pembersihan AC secara rutin.",
  "Gunakan aplikasi pembanding harga tiket hotel.",
  "Jangan biarkan tabungan Anda tergerus inflasi tanpa investasi.",
  "Pahami risiko investasi di sektor energi terbarukan.",
  "Gunakan dana darurat untuk biaya renovasi rumah yang mendesak.",
  "Jangan lupakan biaya iuran keanggotaan profesi.",
  "Gunakan fitur 'spending limit' pada kartu debit.",
  "Pelajari cara investasi di instrumen derivatif dengan sangat hati-hati.",
  "Jangan membeli barang yang tidak ramah lingkungan.",
  "Gunakan asuransi kesehatan untuk hewan peliharaan jika perlu.",
  "Jangan lupakan biaya langganan cloud storage untuk data Anda.",
  "Gunakan aplikasi pengelola tagihan yang bisa otomatis bayar.",
  "Jangan biarkan hutang pajak menumpuk.",
  "Pahami risiko investasi di sektor teknologi informasi.",
  "Gunakan dana khusus untuk membantu korban bencana alam.",
  "Jangan lupakan biaya administrasi saat melakukan top up e-wallet.",
  "Gunakan fitur 'two-factor authentication' pada semua akun keuangan.",
  "Pelajari cara mengelola keuangan saat pindah ke luar kota atau luar negeri.",
  "Jangan membeli barang yang tidak memiliki suku cadang yang mudah dicari.",
  "Gunakan asuransi kesehatan syariah untuk ketenangan pikiran.",
  "Jangan lupakan biaya pemeliharaan sistem keamanan rumah.",
  "Gunakan aplikasi perbandingan harga sewa kendaraan.",
  "Jangan biarkan keinginan untuk cepat kaya membuat Anda terjebak penipuan.",
  "Pahami risiko investasi di sektor pertambangan.",
  "Gunakan dana darurat untuk biaya pemakaman keluarga yang mendadak.",
  "Jangan lupakan biaya iuran keanggotaan klub olahraga.",
  "Gunakan fitur 'cashback' pada aplikasi transportasi online.",
  "Pelajari cara investasi di sektor agribisnis.",
  "Jangan membeli barang yang hanya akan digunakan untuk sekali acara.",
  "Gunakan asuransi jiwa unit link dengan porsi proteksi lebih besar.",
  "Jangan lupakan biaya langganan aplikasi musik tanpa iklan.",
  "Gunakan aplikasi pengelola keuangan yang memiliki fitur AI.",
  "Jangan biarkan hutang menghambat impian Anda.",
  "Pahami risiko investasi di sektor ritel.",
  "Gunakan dana khusus untuk biaya mudik atau pulang kampung.",
  "Jangan lupakan biaya administrasi saat mencairkan reksadana.",
  "Gunakan fitur 'freeze' pada aplikasi bank jika kartu hilang.",
  "Pelajari cara mengelola keuangan saat mendapatkan warisan.",
  "Jangan membeli barang yang tidak sesuai dengan kebutuhan Anda.",
  "Gunakan asuransi kesehatan untuk asisten rumah tangga.",
  "Jangan lupakan biaya pemeliharaan peralatan dapur.",
  "Gunakan aplikasi perbandingan harga perlengkapan bayi.",
  "Jangan biarkan rasa takut menghalangi Anda untuk mulai berinvestasi.",
  "Pahami risiko investasi di sektor perbankan.",
  "Gunakan dana darurat untuk biaya hukum yang tidak terduga.",
  "Jangan lupakan biaya iuran keanggotaan perpustakaan.",
  "Gunakan fitur 'points' pada aplikasi belanja untuk diskon.",
  "Pelajari cara investasi di sektor infrastruktur.",
  "Jangan membeli barang yang tidak memiliki ulasan positif.",
  "Gunakan asuransi jiwa untuk melindungi hutang KPR Anda.",
  "Jangan lupakan biaya langganan aplikasi desain atau produktivitas.",
  "Gunakan aplikasi pengelola keuangan yang bisa mencatat aset kripto.",
  "Jangan biarkan hutang membuat Anda stres dan tidak produktif.",
  "Pahami risiko investasi di sektor manufaktur.",
  "Gunakan dana khusus untuk biaya kurban setiap tahun.",
  "Jangan lupakan biaya administrasi saat melakukan transfer internasional.",
  "Gunakan fitur 'alert' untuk setiap transaksi keluar di rekening.",
  "Pelajari cara mengelola keuangan saat menghadapi masa pengangguran.",
  "Jangan membeli barang yang tidak bisa Anda rawat sendiri.",
  "Gunakan asuransi kesehatan untuk perlindungan saat rawat jalan.",
  "Jangan lupakan biaya pemeliharaan atap rumah agar tidak bocor.",
  "Gunakan aplikasi perbandingan harga obat di apotek.",
  "Jangan biarkan keserakahan membuat Anda mengambil risiko terlalu tinggi.",
  "Pahami risiko investasi di sektor pariwisata.",
  "Gunakan dana darurat untuk biaya perbaikan gadget yang penting untuk kerja.",
  "Jangan lupakan biaya iuran keanggotaan komunitas hobi.",
  "Gunakan fitur 'referral' untuk mendapatkan bonus dari aplikasi keuangan.",
  "Pelajari cara investasi di sektor pendidikan.",
  "Jangan membeli barang yang tidak memiliki layanan purna jual.",
  "Gunakan asuransi jiwa untuk menjamin kelangsungan bisnis keluarga.",
  "Jangan lupakan biaya langganan aplikasi kesehatan atau meditasi.",
  "Gunakan aplikasi pengelola keuangan yang bisa mencatat logam mulia.",
  "Jangan biarkan hutang merusak reputasi profesional Anda.",
  "Pahami risiko investasi di sektor logistik.",
  "Gunakan dana khusus untuk biaya liburan singkat (staycation).",
  "Jangan lupakan biaya administrasi saat melakukan pembayaran kartu kredit.",
  "Gunakan fitur 'hide balance' pada aplikasi bank untuk privasi.",
  "Pelajari cara mengelola keuangan saat memiliki anak berkebutuhan khusus.",
  "Jangan membeli barang yang tidak memiliki sertifikasi keamanan.",
  "Gunakan asuransi kesehatan untuk perlindungan saat kehamilan.",
  "Jangan lupakan biaya pemeliharaan pagar dan halaman rumah.",
  "Gunakan aplikasi perbandingan harga tiket bioskop.",
  "Jangan biarkan ketidaktahuan membuat Anda kehilangan uang.",
  "Pahami risiko investasi di sektor hiburan.",
  "Gunakan dana darurat untuk biaya perbaikan alat rumah tangga utama.",
  "Jangan lupakan biaya iuran keanggotaan asosiasi alumni.",
  "Gunakan fitur 'cash withdrawal' tanpa kartu di ATM.",
  "Pelajari cara investasi di sektor kesehatan.",
  "Jangan membeli barang yang tidak memberikan nilai tambah bagi hidup Anda.",
  "Gunakan asuransi jiwa untuk melindungi masa depan pasangan.",
  "Jangan lupakan biaya langganan aplikasi belajar bahasa asing.",
  "Gunakan aplikasi pengelola keuangan yang bisa mencatat properti.",
  "Jangan biarkan hutang menghalangi Anda untuk menabung.",
  "Pahami risiko investasi di sektor makanan dan minuman.",
  "Gunakan dana khusus untuk biaya perbaikan gadget anak.",
  "Jangan lupakan biaya administrasi saat melakukan penukaran mata uang asing.",
  "Gunakan fitur 'biometric authentication' untuk transaksi e-wallet.",
  "Pelajari cara mengelola keuangan saat menjadi ekspatriat.",
  "Jangan membeli barang yang tidak Anda butuhkan hanya untuk mengisi waktu luang.",
  "Gunakan asuransi kesehatan untuk perlindungan saat di luar negeri.",
  "Jangan lupakan biaya pemeliharaan saluran air dan septik tank.",
  "Gunakan aplikasi perbandingan harga sewa apartemen atau rumah.",
  "Jangan biarkan rasa malas membuat Anda tidak memantau keuangan.",
  "Pahami risiko investasi di sektor telekomunikasi.",
  "Gunakan dana darurat untuk biaya perbaikan sistem kelistrikan rumah.",
  "Jangan lupakan biaya iuran keanggotaan klub buku.",
  "Gunakan fitur 'promo code' saat melakukan transaksi online.",
  "Pelajari cara investasi di sektor energi.",
  "Jangan membeli barang yang tidak memiliki instruksi penggunaan yang jelas.",
  "Gunakan asuransi jiwa untuk menjamin biaya pemakaman.",
  "Jangan lupakan biaya langganan aplikasi berita atau informasi bisnis.",
  "Gunakan aplikasi pengelola keuangan yang bisa mencatat koleksi barang berharga.",
  "Jangan biarkan hutang membuat Anda kehilangan kepercayaan diri.",
  "Pahami risiko investasi di sektor otomotif.",
  "Gunakan dana khusus untuk biaya perayaan hari jadi pernikahan.",
  "Jangan lupakan biaya administrasi saat melakukan pembayaran pajak.",
  "Gunakan fitur 'transaction history' untuk audit pengeluaran mingguan.",
  "Pelajari cara mengelola keuangan saat memiliki bisnis keluarga.",
  "Jangan membeli barang yang tidak memberikan kebahagiaan jangka panjang.",
  "Gunakan asuransi kesehatan untuk perlindungan dari penyakit menular.",
  "Jangan lupakan biaya pemeliharaan jendela dan pintu rumah.",
  "Gunakan aplikasi perbandingan harga paket wisata.",
  "Jangan biarkan kesombongan membuat Anda tidak mau belajar keuangan.",
  "Pahami risiko investasi di sektor media.",
  "Gunakan dana darurat untuk biaya perbaikan atap yang bocor saat hujan.",
  "Jangan lupakan biaya iuran keanggotaan komunitas investasi.",
  "Gunakan fitur 'points exchange' untuk mendapatkan barang gratis.",
  "Pelajari cara investasi di sektor properti komersial.",
  "Jangan membeli barang yang tidak sesuai dengan gaya hidup sehat Anda.",
  "Gunakan asuransi jiwa untuk melindungi aset yang sedang dicicil.",
  "Jangan lupakan biaya langganan aplikasi produktivitas tim.",
  "Gunakan aplikasi pengelola keuangan yang bisa mencatat investasi P2P.",
  "Jangan biarkan hutang merusak masa depan Anda.",
  "Pahami risiko investasi di sektor jasa keuangan.",
  "Gunakan dana khusus untuk biaya perbaikan gadget pasangan.",
  "Jangan lupakan biaya administrasi saat melakukan transfer ke luar negeri.",
  "Gunakan fitur 'recurring payment' untuk tagihan rutin.",
  "Pelajari cara mengelola keuangan saat menghadapi perceraian.",
  "Jangan membeli barang yang tidak memiliki dukungan komunitas yang baik.",
  "Gunakan asuransi kesehatan untuk perlindungan dari kecelakaan kerja.",
  "Jangan lupakan biaya pemeliharaan dinding dan cat rumah.",
  "Gunakan aplikasi perbandingan harga perlengkapan olahraga.",
  "Jangan biarkan rasa bersalah membuat Anda memberikan uang secara berlebihan.",
  "Pahami risiko investasi di sektor e-commerce.",
  "Gunakan dana darurat untuk biaya perbaikan kendaraan yang mogok.",
  "Jangan lupakan biaya iuran keanggotaan klub seni.",
  "Gunakan fitur 'referral code' untuk mendapatkan diskon belanja.",
  "Pelajari cara investasi di sektor teknologi finansial.",
  "Jangan membeli barang yang tidak memiliki standar kualitas nasional.",
  "Gunakan asuransi jiwa untuk menjamin kelangsungan pendidikan anak.",
  "Jangan lupakan biaya langganan aplikasi hiburan anak.",
  "Gunakan aplikasi pengelola keuangan yang bisa mencatat dana pensiun.",
  "Jangan biarkan hutang membuat Anda merasa terjebak.",
  "Pahami risiko investasi di sektor asuransi.",
  "Gunakan dana khusus untuk biaya perayaan kelulusan anak.",
  "Jangan lupakan biaya administrasi saat melakukan pembayaran iuran BPJS.",
  "Gunakan fitur 'security alert' untuk aktivitas login yang mencurigakan.",
  "Pelajari cara mengelola keuangan saat menjadi digital nomad.",
  "Jangan membeli barang yang tidak memberikan manfaat jangka panjang.",
  "Gunakan asuransi kesehatan untuk perlindungan dari penyakit kritis.",
  "Jangan lupakan biaya pemeliharaan sistem air minum di rumah.",
  "Gunakan aplikasi perbandingan harga perlengkapan rumah tangga.",
  "Jangan biarkan rasa takut ketinggalan membuat Anda boros.",
  "Pahami risiko investasi di sektor real estate.",
  "Gunakan dana darurat untuk biaya perbaikan gadget yang rusak total.",
  "Jangan lupakan biaya iuran keanggotaan komunitas pecinta alam.",
  "Gunakan fitur 'cashback' untuk setiap transaksi belanja bulanan.",
  "Pelajari cara investasi di sektor berkelanjutan.",
  "Jangan membeli barang yang tidak Anda butuhkan hanya untuk pamer di media sosial.",
  "Gunakan asuransi jiwa untuk melindungi keluarga dari beban hutang.",
  "Jangan lupakan biaya langganan aplikasi pengolah foto atau video.",
  "Gunakan aplikasi pengelola keuangan yang bisa mencatat tabungan emas.",
  "Jangan biarkan hutang merusak kedamaian pikiran Anda.",
  "Pahami risiko investasi di sektor energi fosil.",
  "Gunakan dana khusus untuk biaya perbaikan rumah yang mendadak.",
  "Jangan lupakan biaya administrasi saat melakukan pembayaran tagihan listrik.",
  "Gunakan fitur 'auto-debit' untuk menabung secara otomatis.",
  "Pelajari cara mengelola keuangan saat menghadapi masa pensiun dini.",
  "Jangan membeli barang yang tidak memberikan nilai tambah bagi produktivitas Anda.",
  "Gunakan asuransi kesehatan untuk perlindungan saat rawat inap.",
  "Jangan lupakan biaya pemeliharaan kendaraan agar tetap aman digunakan.",
  "Gunakan aplikasi perbandingan harga tiket kereta api.",
  "Jangan biarkan keinginan untuk terlihat kaya membuat Anda miskin.",
  "Pahami risiko investasi di sektor pertambangan emas.",
  "Gunakan dana darurat untuk biaya perbaikan rumah yang terkena bencana.",
  "Jangan lupakan biaya iuran keanggotaan klub pecinta hewan.",
  "Gunakan fitur 'discount' untuk setiap transaksi belanja di hari tertentu.",
  "Pelajari cara investasi di sektor teknologi medis.",
  "Jangan membeli barang yang tidak memiliki garansi purna jual.",
  "Gunakan asuransi jiwa untuk menjamin masa depan keluarga.",
  "Jangan lupakan biaya langganan aplikasi belajar online.",
  "Gunakan aplikasi pengelola keuangan yang bisa mencatat semua aset Anda.",
  "Jangan biarkan hutang menghambat langkah Anda menuju kebebasan finansial.",
  "Pahami risiko investasi di sektor properti residensial.",
  "Gunakan dana khusus untuk biaya perayaan hari raya keagamaan.",
  "Jangan lupakan biaya administrasi saat melakukan pembayaran tagihan air.",
  "Gunakan fitur 'budgeting' untuk mengontrol pengeluaran harian.",
  "Pelajari cara mengelola keuangan saat menghadapi krisis kesehatan.",
  "Jangan membeli barang yang tidak memberikan manfaat bagi kesehatan Anda.",
  "Gunakan asuransi kesehatan untuk perlindungan dari risiko kecelakaan.",
  "Jangan lupakan biaya pemeliharaan rumah agar tetap nyaman dihuni.",
  "Gunakan aplikasi perbandingan harga tiket bus.",
  "Jangan biarkan rasa iri membuat Anda menghabiskan uang secara tidak bijak.",
  "Pahami risiko investasi di sektor teknologi informasi dan komunikasi.",
  "Gunakan dana darurat untuk biaya perbaikan gadget yang sangat diperlukan.",
  "Jangan lupakan biaya iuran keanggotaan komunitas sosial.",
  "Gunakan fitur 'reward' untuk setiap transaksi yang Anda lakukan.",
  "Pelajari cara investasi di sektor energi terbarukan dan ramah lingkungan.",
  "Jangan membeli barang yang tidak memberikan kebahagiaan bagi Anda dan keluarga.",
  "Gunakan asuransi jiwa untuk melindungi masa depan orang-orang yang Anda cintai.",
  "Jangan lupakan biaya langganan aplikasi yang memberikan informasi bermanfaat.",
  "Gunakan aplikasi pengelola keuangan yang mudah digunakan dan aman.",
  "Jangan biarkan hutang mengendalikan hidup Anda, jadilah tuan atas uang Anda sendiri."
];
